# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 693)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 50, 511, 221))
        self.groupBox.setObjectName("groupBox")
        self.table_instructions = QtWidgets.QTableWidget(self.groupBox)
        self.table_instructions.setGeometry(QtCore.QRect(10, 20, 491, 201))
        self.table_instructions.setObjectName("table_instructions")
        self.table_instructions.setColumnCount(8)
        self.table_instructions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_instructions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_instructions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_instructions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_instructions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_instructions.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_instructions.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_instructions.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_instructions.setHorizontalHeaderItem(7, item)
        self.table_instructions.horizontalHeader().setDefaultSectionSize(60)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 50, 611, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.table_funcuints = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_funcuints.setGeometry(QtCore.QRect(0, 20, 611, 201))
        self.table_funcuints.setShowGrid(True)
        self.table_funcuints.setObjectName("table_funcuints")
        self.table_funcuints.setColumnCount(11)
        self.table_funcuints.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_funcuints.setHorizontalHeaderItem(10, item)
        self.table_funcuints.horizontalHeader().setDefaultSectionSize(55)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 280, 1141, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.table_registers = QtWidgets.QTableWidget(self.groupBox_3)
        self.table_registers.setGeometry(QtCore.QRect(10, 20, 1121, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.table_registers.setFont(font)
        self.table_registers.setObjectName("table_registers")
        self.table_registers.setColumnCount(0)
        self.table_registers.setRowCount(0)
        self.table_registers.horizontalHeader().setVisible(True)
        self.table_registers.horizontalHeader().setDefaultSectionSize(40)
        self.table_fregisters = QtWidgets.QTableWidget(self.groupBox_3)
        self.table_fregisters.setGeometry(QtCore.QRect(10, 80, 1121, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.table_fregisters.setFont(font)
        self.table_fregisters.setObjectName("table_fregisters")
        self.table_fregisters.setColumnCount(0)
        self.table_fregisters.setRowCount(0)
        self.table_fregisters.horizontalHeader().setDefaultSectionSize(40)
        self.table_values = QtWidgets.QTableWidget(self.groupBox_3)
        self.table_values.setGeometry(QtCore.QRect(10, 140, 1121, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.table_values.setFont(font)
        self.table_values.setObjectName("table_values")
        self.table_values.setColumnCount(0)
        self.table_values.setRowCount(0)
        self.table_values.horizontalHeader().setDefaultSectionSize(40)
        self.table_fvalues = QtWidgets.QTableWidget(self.groupBox_3)
        self.table_fvalues.setGeometry(QtCore.QRect(10, 200, 1121, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.table_fvalues.setFont(font)
        self.table_fvalues.setObjectName("table_fvalues")
        self.table_fvalues.setColumnCount(0)
        self.table_fvalues.setRowCount(0)
        self.table_fvalues.horizontalHeader().setDefaultSectionSize(40)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(440, 10, 703, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_current = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_current.setObjectName("label_current")
        self.horizontalLayout.addWidget(self.label_current)
        self.label_cycle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cycle.sizePolicy().hasHeightForWidth())
        self.label_cycle.setSizePolicy(sizePolicy)
        self.label_cycle.setMinimumSize(QtCore.QSize(50, 20))
        self.label_cycle.setBaseSize(QtCore.QSize(50, 50))
        self.label_cycle.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"color: rgb(239, 41, 41);\n"
"")
        self.label_cycle.setScaledContents(False)
        self.label_cycle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycle.setObjectName("label_cycle")
        self.horizontalLayout.addWidget(self.label_cycle)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineedit_cycle = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_cycle.sizePolicy().hasHeightForWidth())
        self.lineedit_cycle.setSizePolicy(sizePolicy)
        self.lineedit_cycle.setMaximumSize(QtCore.QSize(62, 16777215))
        self.lineedit_cycle.setAlignment(QtCore.Qt.AlignCenter)
        self.lineedit_cycle.setObjectName("lineedit_cycle")
        self.horizontalLayout.addWidget(self.lineedit_cycle)
        self.btn_loadfile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_loadfile.setObjectName("btn_loadfile")
        self.horizontalLayout.addWidget(self.btn_loadfile)
        self.btn_run = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_run.sizePolicy().hasHeightForWidth())
        self.btn_run.setSizePolicy(sizePolicy)
        self.btn_run.setFlat(False)
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayout.addWidget(self.btn_run)
        self.btn_pause = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.btn_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.btn_setting = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_setting.setObjectName("btn_setting")
        self.horizontalLayout.addWidget(self.btn_setting)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 560, 1131, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.run_info = QtWidgets.QTextBrowser(self.groupBox_4)
        self.run_info.setGeometry(QtCore.QRect(10, 30, 1111, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.run_info.setFont(font)
        self.run_info.setObjectName("run_info")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scoreboard Alogorithm Simulator"))
        self.groupBox.setTitle(_translate("MainWindow", "Instruction Status"))
        item = self.table_instructions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Instruction"))
        item = self.table_instructions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "i"))
        item = self.table_instructions.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "j"))
        item = self.table_instructions.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "k"))
        item = self.table_instructions.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Issue"))
        item = self.table_instructions.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Read Operands"))
        item = self.table_instructions.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Execution Complete"))
        item = self.table_instructions.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Write Result"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Functional unit status"))
        item = self.table_funcuints.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.table_funcuints.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_funcuints.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Busy"))
        item = self.table_funcuints.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Op"))
        item = self.table_funcuints.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Dest Fi"))
        item = self.table_funcuints.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fj"))
        item = self.table_funcuints.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fk"))
        item = self.table_funcuints.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Qj"))
        item = self.table_funcuints.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Qk"))
        item = self.table_funcuints.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Rj"))
        item = self.table_funcuints.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Rk"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Register Status"))
        self.label.setText(_translate("MainWindow", "Scoreboard Alogrithm Simulator"))
        self.label_current.setText(_translate("MainWindow", "Current Cycle"))
        self.label_cycle.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Cycle"))
        self.btn_loadfile.setText(_translate("MainWindow", "Load File"))
        self.btn_run.setText(_translate("MainWindow", "Run"))
        self.btn_pause.setText(_translate("MainWindow", "Pause"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_setting.setText(_translate("MainWindow", "setting"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Running Informations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

